apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: get-aws-creds
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: ecr_name
        value: "ecr-csp"
      - name: worker_nodes_role_name
        value: "eks-node-group-role"
      - name: default_region
        value: "eu-west-1"
      - name: ecr_region
        value: "us-west-2"

  workflowTemplateRef:
    name: get-aws-creds